### ISSUE TITLE
Missing module 'debug'

### ISSUE THREAD

**Issue by kokarn** [zaaack/keyv-file#6]
Hello!

Tried to set this up with a super basic example and `got`

```
const got = require( 'got' );
const Keyv = require( 'keyv' );
const KeyvFile = require( 'keyv-file' );

const keyv = new Keyv( {
    store: new KeyvFile( {
        filename: CACHE_PATH,
    } ),
} );
```

This fails on the first request of `got` with 
```
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/my-proj/node_modules/keyv-file/lib/index.js:6:41)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

Running `npm i debug` resolves this issue.

Is debug supposed to be added or is this something that shouldn't be available in the production version?

**Comment by zaaack** [comment]
@kokarn Sorry, looks I forgot to add debug module to `dependencies` in package.json, this is fixed in `keyv-file@0.1.10`, thanks for reporting! 👍
